services:
  nginx-proxy:
    image: public.ecr.aws/nginx/nginx:1.27.1-alpine3.20-perl
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    ports:
      - "80:80"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:80/health-check || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
